### ISSUE TITLE
KVCacheServer 编译错误

### ISSUE THREAD

**Issue by njdragonfly** [Tencent/DCache#10]
./jmem_hashmap_malloc/dcache_jmem_hashmap_malloc.h: In member function ‘int tars::HashMapMallocDCache<LockPolicy, StorePolicy>::eraseHashByForce(size_t, C)’:
./jmem_hashmap_malloc/dcache_jmem_hashmap_malloc.h:353:65: error: expected primary-expression before ‘>’ token
             return _hashMapVec[h%_jmemNum]->eraseHashByForce<C>(h, c);
                                                                 ^
./jmem_hashmap_malloc/dcache_jmem_hashmap_malloc.h: In member function ‘int tars::HashMapMallocDCache<LockPolicy, StorePolicy>::eraseHashByForce(size_t, C, std::vector<std::__cxx11::basic_string<char> >&)’:
./jmem_hashmap_malloc/dcache_jmem_hashmap_malloc.h:359:63: error: expected primary-expression before ‘>’ token
             return _hashMapVec[h%_jmemNum]->eraseHashByForce<C>(h, c, vDelK);
                                                               ^
./jmem_hashmap_malloc/dcache_jmem_hashmap_malloc.h: In member function ‘int tars::HashMapMallocDCache<LockPolicy, StorePolicy>::getHash(size_t, std::vector<std::pair<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> > >&, C)’:
./jmem_hashmap_malloc/dcache_jmem_hashmap_malloc.h:365:54: error: expected primary-expression before ‘>’ token
             return _hashMapVec[h%_jmemNum]->getHash<C>(h, vv, c);
                                                      ^
./jmem_hashmap_malloc/dcache_jmem_hashmap_malloc.h: In member function ‘int tars::HashMapMallocDCache<LockPolicy, StorePolicy>::getHash(size_t, std::vector<typename tars::JmemHashMapMalloc<LockPolicy, StorePolicy>::ToDoFunctor::DataRecord>&, C)’:
./jmem_hashmap_malloc/dcache_jmem_hashmap_malloc.h:371:54: error: expected primary-expression before ‘>’ token
             return _hashMapVec[h%_jmemNum]->getHash<C>(h, vv, c);
                                                      ^
./jmem_hashmap_malloc/dcache_jmem_hashmap_malloc.h: In member function ‘int tars::HashMapMallocDCache<LockPolicy, StorePolicy>::getHashWithOnlyKey(size_t, std::vector<typename tars::JmemHashMapMalloc<LockPolicy, StorePolicy>::ToDoFunctor::DataRecord>&, C)’:
./jmem_hashmap_malloc/dcache_jmem_hashmap_malloc.h:377:65: error: expected primary-expression before ‘>’ token
             return _hashMapVec[h%_jmemNum]->getHashWithOnlyKey<C>(h, vv, c);
                                                                 ^
./jmem_hashmap_malloc/dcache_jmem_hashmap_malloc.h: In member function ‘int tars::HashMapMallocDCache<LockPolicy, StorePolicy>::syncOnce(uint32_t, C&)’:
./jmem_hashmap_malloc/dcache_jmem_hashmap_malloc.h:490:56: error: expected primary-expression before ‘>’ token
                 iRetVec[i] = _hashMapVec[i]->syncOnce<C>(iNowTime, c);

**Comment by njdragonfly** [comment]
GCC版本：
gcc version 7.3.0 (Ubuntu 7.3.0-27ubuntu1~18.04)

**Comment by shanbaoyin** [comment]
i'm using gcc 4.8.5. i will check it with gcc 7.3.0

**Comment by shanbaoyin** [comment]
建议使用gcc 4.8.5, tars在高版本的gcc下不稳定
