### ISSUE TITLE
EraseThread  CPU 100%

### ISSUE THREAD

**Issue by htner** [Tencent/DCache#12]
kkv的模式下，EraseThread 在只有一个mainkey 装满内存，会死loop。 请问应该怎样处理

tc_multi_hashmap_malloc.cpp:8626
                        // 将脏数据移动到get链的头部，使可以继续淘汰
                        if (_pHead->_iGetHead == iAddr)
                        {
                            // 既是头也是尾，只有一个元素了
                            return RT_OK;
                        }

**Comment by shanbaoyin** [comment]
一个mainkey装满内存，这说明你的表结构字段设计不合理。一个miankey下的数据最好不要超过2w条
