### ISSUE TITLE
t_router_switch 表缺失，程序报错

### ISSUE THREAD

**Issue by sofire** [Tencent/DCache#14]
简单看了下 程序，感觉少建了这个表。请确认。

DbHandle::insertSwitchInfo\|[TC_Mysql::execute]: mysql_query: [ insert into `t_router_switch` (`app_name`,`module_name`,`group_name`,`master_server`,`slave_server`,`mirror_idc`,`master_mirror`,`slave_mirror`,`switch_type`,`switch_result`,`access_status`,`comment`,`switch_property`,`switch_time`,`modify_time`) values((select app_name from t_router_app where router_name='DCache.DCache3RouterServer'),'DCache3Test1','DCache3Test1KVGroup1','DCache.DCache3Test1KVCacheServer1-1','DCache.DCache3Test1KVCacheServer1-2','','','',0,3,0,'SwitchThread:: slaveBinlogdif diffBinlogTime(1556264300) > 300 DCache.DCache3Test1KVCacheServer1-2','auto',FROM_UNIXTIME(1556264568), now()) ] :Table 'db_dcache_relation.t_router_switch' doesn't exist
-- | -- | --

**Comment by shanbaoyin** [comment]
是的，因为目前体验版还没有加入主备切换、服务扩容的功能，所以这个表还没有，1.0版本会完善
