### ISSUE TITLE
后台管理系统使用的是没有文档的内部VUE框架

### ISSUE THREAD

**Issue by llwwjjj** [Tencent/DCache#15]
后台管理系统使用的是没有文档的内部VUE框架：let-ui ，似乎是腾讯内部的一个前端框架，找遍网络也没有看到ui文档，是否应该换为文档更丰富的开源框架以便二次开发呢？

**Comment by shanbaoyin** [comment]
@JSFiend 杰哥解答一下

**Comment by JSFiend** [comment]
这个是和阅文集团合作的 ui 框架，  有文档的，地址： https://qidian.gtimg.com/let/index.html
