### ISSUE TITLE
尽管KVCacheServer支持自动淘汰数据，但setKV没有去db找数据，数据一致性缺乏保证

### ISSUE THREAD

**Issue by llwwjjj** [Tencent/DCache#16]
尽管KVCacheServer支持自动淘汰数据，但写数据时（如setKV）没有去db找数据，数据一致性缺乏保证：
如setKV[接口](https://github.com/Tencent/DCache/blob/master/src/KVCacheServer/WCacheImp.cpp#L1349)，
但是在getKV却会在没找到数据时去db[查询](https://github.com/Tencent/DCache/blob/master/src/KVCacheServer/CacheImp.cpp#L549)，虽然不太熟悉源码，但感觉应该是个bug吧？

**Comment by shanbaoyin** [comment]
数据覆盖写，没有问题。

**Comment by llwwjjj** [comment]
感谢解答，还想请问一下在updateKV时，如果我想要更新带有insert语义，也就是用SUB_INSERT/ADD_INSERT 的时候，也是没有去db查询的[覆盖性更新](https://github.com/Tencent/DCache/blob/5068b701b9aa3b72ee76618cd94fb4b68343f19c/src/KVCacheServer/jmem_hashmap_malloc/tc_hashmap_malloc.cpp#L2870)，那么如果缓存数据被淘汰了是不是会引起不一致性？
