### ISSUE TITLE
update与writeBinLog之间未加锁

### ISSUE THREAD

**Issue by llwwjjj** [Tencent/DCache#18]
当有多个update请求时，由于update与writeBinLog之间[未加锁](https://github.com/Tencent/DCache/blob/5068b701b9aa3b72ee76618cd94fb4b68343f19c/src/MKVCacheServer/MKWCacheImp.cpp#L4006),是否会引起BinLog乱序的问题，最终导致备机数据与主机不一致？

**Comment by shanbaoyin** [comment]
存在这种可能性，但概率极低。
