### ISSUE TITLE
when to support the version of Java ？

### ISSUE THREAD

**Issue by wanbf** [Tencent/DCache#2]

**Comment by shanbaoyin** [comment]
we will develop java SDK, may be opened in Q4 2019.

**Comment by wanbf** [comment]
OK  ths

**Comment by walkertest** [comment]
> we will develop java SDK, may be opened in Q4 2019.

maybe you can create a repo and let the people of community to realize it.

Our team has developed a simple java sdk to visit dcache server and use it online.

**Comment by evilstar2016** [comment]
Today is 2020.1.10
