### ISSUE TITLE
DCache部署过程的一些疑问

### ISSUE THREAD

**Issue by SherLockOD** [Tencent/DCache#20]
1. Cache模块的部署目前只有主备模式吗？是否支持对主备节点进行扩容？
2. DbAccess对接后端存储有计划出操作文档吗？
3. 是否有计划组建交流讨论群？

**Comment by shanbaoyin** [comment]
1、主+备+多地镜像的模式，你也可以把备机、镜像下线，只保留主机。 扩容功能将在1.0发布。
2、DbAccess由用户自己开发，然后在模块配置中设置/Main/DbAccess下的配置项即可。后续会出文档。
3、有疑问可以在github提issue，技术交流群的模式不可持续
