### ISSUE TITLE
校验值接口日志有待改进

### ISSUE THREAD

**Issue by CoderMansha** [Tencent/DCache#27]
![image](https://user-images.githubusercontent.com/19776677/63635304-e2425180-c693-11e9-8190-06e4705f46d2.png)
校验值接口日志在校验出错时，不打印哪个字段报错，导致字段较多时排查较为耗时，建议可以如截图将字段名也打印出来，体验更好

**Comment by shanbaoyin** [comment]
很好的建议，这块日志信息的确不够完善，欢迎直接修改提pull request给我们，期待你的参与
