### ISSUE TITLE
TarsFramework v2.4.7, when creating Application, the IDC area cannot be empty

### ISSUE THREAD

**Issue by bartdong** [Tencent/DCache#43]
![image](https://user-images.githubusercontent.com/27182433/88667122-8984ff80-d113-11ea-8644-0f7854b1329d.png)
When creating Application, the IDC area cannot be empty. But I cannot find where to config the IDC area.
创建应用的时候，提示IDC地区参数不能为空，但是又找不到哪里可以配置IDC的地方。而且这个选项也没显示必填项。

**Comment by ruanshudong** [comment]
第三个tab: region, 创建地区

**Comment by bartdong** [comment]
原来在这里，感谢！后面建议在界面上增加相关指引。
