### ISSUE TITLE
Compile failed...

### ISSUE THREAD

**Issue by xinfenglee** [Tencent/DCache#51]
[root@test1 build]# make
Scanning dependencies of target TarsComm
[  1%] /usr/local/tars/cpp/tools/tars2cpp --with-tars /code/DCache-master/src/TarsComm/CacheShare.tars
[  1%] /usr/local/tars/cpp/tools/tars2cpp --with-tars /code/DCache-master/src/TarsComm/DbAccess.tars
[  1%] /usr/local/tars/cpp/tools/tars2cpp --with-tars /code/DCache-master/src/TarsComm/ProxyShare.tars
[  1%] Built target TarsComm
Scanning dependencies of target tars-RouterServer
[  2%] /usr/local/tars/cpp/tools/tars2cpp --with-tars /code/DCache-master/src/Router/Router.tars
[  2%] /usr/local/tars/cpp/tools/tars2cpp --with-tars /code/DCache-master/src/Router/RouterClient.tars
[  3%] /usr/local/tars/cpp/tools/tars2cpp --with-tars /code/DCache-master/src/Router/RouterShare.tars
[  3%] Built target tars-RouterServer
Scanning dependencies of target RouterServer
[  3%] Building CXX object src/Router/CMakeFiles/RouterServer.dir/DbHandle.cpp.o
[  3%] Building CXX object src/Router/CMakeFiles/RouterServer.dir/RouterImp.cpp.o
/code/DCache-master/src/Router/RouterImp.cpp: In member function ?€?virtual void RouterImp::initialize()?€?:
/code/DCache-master/src/Router/RouterImp.cpp:93:50: error: cannot call member function ?€?tars::TC_EpollServerPtr& tars::Application::getEpollServer()?€? without object
     TC_Endpoint ep = Application::getEpollServer()->getBindAdapter(adapter)->getEndpoint();
                                                  ^
make[2]: *** [src/Router/CMakeFiles/RouterServer.dir/RouterImp.cpp.o] Error 1
make[1]: *** [src/Router/CMakeFiles/RouterServer.dir/all] Error 2
make: *** [all] Error 2

**Comment by ruanshudong** [comment]
稍微等一下, 新版本tarscpp升级了接口, 导致编译有点问题

**Comment by xinfenglee** [comment]
哦哦 谢谢
