### ISSUE TITLE
DCache创建的时候服务由于文件权限问题而无法启动

### ISSUE THREAD

**Issue by cosmosir** [Tencent/DCache#85]
需要到具体目录开通权限，然后在操作web上重启，才可以正常拉起来 。
是需要提前设置什么么？
/usr/local/app/tars/tarsnode/data/DCache.*/bin

另外 ProxyServer有报错，但是服务状态是正常的
2022-06-01 13:44:20 | DCache.TarsGameProxyServer_172.25.0.5 | 140431755515648 | [RouterTableInfoFactory::checkModuleChange] RouterHandle::getInstance()->getModuleList error!

**Comment by ruanshudong** [comment]
dcache服务都没有可执行权限?

**Comment by cosmosir** [comment]
看样子是的
我的操作是DCache编译完成后，将所有tgz包拷贝到另外一台虚拟机，然后执行install.sh上传打包文件
拷贝的过程中会丢失权限吗？

**Comment by ruanshudong** [comment]
那看你怎么copy的了, 你可以检查一下你copy以后的文件权限

**Comment by cosmosir** [comment]
> tarsweb右上角是什么版本

web:3.0.0
framework:3.0.6

**Comment by ruanshudong** [comment]
看起来是你自己问题, 框架应该没这个bug

**Comment by cosmosir** [comment]
感谢回答

DCache是否可以成类似tars-framework那样的容器，这样部署就方便多了
